-- MySQL Script generated by MySQL Workbench
-- 10/21/16 20:38:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tweeter_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tweeter_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tweeter_api` DEFAULT CHARACTER SET utf8 ;
USE `tweeter_api` ;

-- -----------------------------------------------------
-- Table `tweeter_api`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter_api`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL,
  `oauth` VARCHAR(64) NULL DEFAULT NULL,
  `oauth_secret` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tweeter_api`.`saved_tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweeter_api`.`saved_tweets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tweeter_id` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_saved_tweets_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_saved_tweets_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tweeter_api`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
